#!/usr/bin/env php
<?php


require __DIR__.'/vendor/autoload.php';

use JiJiHoHoCoCo\IchiORM\Command\ModelCommand;
use JiJiHoHoCoCo\IchiRoute\Command\RouteCommand;
use JiJiHoHoCoCo\IchiTemplate\Command\TemplateCommand;
use JiJiHoHoCoCo\IchiValidation\Command\ValidationCommand;

$modelCommand=new ModelCommand;
$modelCommand->run(__DIR__,$argv);

$routeCommand=new RouteCommand;
$routeCommand->run(__DIR__,$argv);

$templateCommand=new TemplateCommand;
$templateCommand->run(__DIR__,$argv);

$validationCommand=new ValidationCommand;
$validationCommand->run(__DIR__,$argv);

